version: '3'
services:
  app:
    container_name: learn-react
    stdin_open: true
    tty: true
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # - /app/node_modules
      - ./:/app
    # command: sh -c "cd react-sample && yarn start"
    command: sh -c "yarn install && yarn dev"
    ports:
      - '3000:3000'
 